jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn lint
          name: Run ESLint
      - run:
          command: yarn compile
          name: Compile
      - run:
          command: yarn test
          name: Jest
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
orbs:
  rn: react-native-community/react-native@1.2.1
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - hold_build_android_debug:
          type: approval
          requires:
           - analyse_js
      - rn/android_build:
          build_type: debug
          name: build_android_debug
          project_path: android
          requires:
            - hold_build_android_debug
      - hold_build_android_release:
          type: approval
          requires:
           - analyse_js
      - rn/android_build:
          build_type: release
          name: build_android_release
          project_path: android
          requires:
            - hold_build_android_release
