name: Lint and build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn
    - name: Run ESLint
      run: yarn lint
    - name: Compile
      run: yarn compile
    - name: Jest
      run: yarn test
  build-android:
    needs: lint
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn
    - name: Compile
      run: yarn compile
    - name: Download gradle dependencies
      run: ./gradlew dependencies
      working-directory: android
    - name: Set Debug keystore
      run: echo ${{ secrets.ANDROID_DEBUG_KEYSTORE }} | base64 -d > android/app/debug.keystore
    - name: Build Android debug
      run: ./gradlew assembleDebug
      working-directory: android
    - name: Archive APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: android/app/build/outputs/apk
